#!/usr/bin/perl

if ( $< != 0 ) {
	print "This script must be run as root\n";
	exit (0);
}

system('clear');

print "\n\n\n\n\n\nThis script builds the Alfheim Linux Live disc!\n\n";
print "It is part of the Alfheim Software Initiative.\nIt is released under the HLIN Public License v.2.0.\n";

print "\nPress Enter to continue: ";
my $resp1 = <STDIN>;

system('clear');

use strict;
use warnings;

print "\n\n\n\n\n\nThis script requires Perl's File::Slurp module.\n\n";
print "In order to make sure that we have the current version we will install the newest version here.
Do note that if you haven't used CPAN yet on the system it will ask if you want to configure it.
The default configuration is fine for this project.";

print "\n\nPress Enter to continue: ";
my $resp2 = <STDIN>;

my $script_path = \$ENV{PWD};

system('cpan install File::Slurp');
print "\n\n";

system('clear');

sub menu {
	my @items = @_;

	my $count = 0;
	foreach my $item( @items ) {
		printf "%d: %s\n", ++$count, $item->{text};
	}

	print "\nChoose an option? : ";

	while( my $line = <STDIN> ) {
		chomp $line;
		if ( $line =~ m/\d+/ && $line <= @items ) {
			return $items[ $line - 1 ]{code}->();
		}

		print "\nInvalid input\n\n?: ";
	}
}

my @menu_choices;
my @menu_arch;
my @menu_debian;
my @menu_fedora;
my @menu_gentoo;

@menu_choices = (
	{ text  => 'Arch Based Distribution',
		code  => sub { menu( @menu_arch ) } },
	{ text  => 'Debian Based Distribution',
		code  => sub { menu( @menu_debian ) } },
	{ text  => 'Fedora Based Distribution',
		code  => sub { menu( @menu_fedora ) } },
	{ text  => 'Gentoo Based Distribution',
		code  => sub { menu( @menu_gentoo ) } },
	{ text  => 'View the License for Alfheim Software',
    		code  => sub { exec ('./license') } },
	{ text  => 'Exit',
		code  => sub { print "Thanks for choosing Alfheim!\n" } }
);

@menu_arch = (
	{ text  => 'Create a non-systemd disc (preferred)',
		code  => sub { exec ('scripts/alnsd/alnsd') } },
	{ text  => 'Create a systemd disc (discouraged, non-working)',
		code  => sub { exec ('scripts/alsd/alsd') } },
	{ text  => 'View the License for Alfheim Software',
    		code  => sub { exec ('./license') } },
	{ text => 'Main Menu',
		code => sub { menu( @menu_choices ) } },
	{ text  => 'Exit',
		code  => sub { print "Thanks for choosing Alfheim!\n" } }
);

@menu_debian = (
	{ text  => 'Create a non-systemd disc (preferred)',
		code  => sub { exec ('scripts/dlnsd/dlnsd') } },
	{ text  => 'Create a systemd disc (discouraged, non-working)',
		code  => sub { exec ('scripts/dlsd/dlsd') } },
	{ text  => 'View the License for Alfheim Software',
    		code  => sub { exec ('./license') } },
	{ text => 'Main Menu',
		code => sub { menu( @menu_choices ) } },
	{ text  => 'Exit',
		code  => sub { print "Thanks for choosing Alfheim!\n" } }
);

@menu_fedora = (
	{ text  => 'Create a non-systemd disc (preferred)',
		code  => sub { exec ('scripts/flnsd/flnsd') } },
	{ text  => 'Create a systemd disc (discouraged, non-working)',
		code  => sub { exec ('scripts/flsd/flsd') } },
	{ text  => 'View the License for Alfheim Software',
    		code  => sub { exec ('./license') } },
	{ text => 'Main Menu',
		code => sub { menu( @menu_choices ) } },
	{ text  => 'Exit',
		code  => sub { print "Thanks for choosing Alfheim!\n" } }
);

@menu_gentoo = (
	{ text  => 'Create a non-systemd disc (preferred)',
		code  => sub { exec ('scripts/glnsd/glnsd') } },
	{ text  => 'Create a systemd disc (discouraged, non-working)',
		code  => sub { exec ('scripts/glsd/glsd') } },
	{ text  => 'View the License for Alfheim Software',
    		code  => sub { exec ('./license') } },
	{ text => 'Main Menu',
		code => sub { menu( @menu_choices ) } },
	{ text  => 'Exit',
		code  => sub { print "Thanks for choosing Alfheim!\n" } }
);

print "\n\n\n";
menu( @menu_choices );
