#!/usr/bin/perl

if ( $< != 0 ) {
	print "This script must be run as root\n";
	exit (0);
}

print "\nWelcome to Alfheim Linux non-systemd Build Toolkit!\n";
print "Here we are going to work together to build the best system\n";
print "that we can to suit your needs.  A lot of the software that\n";
print "may use on a regular basis may not be installed right out of\n";
print "the gate but we will do our best to accomodate you.\n";

print "\nThank you for choosing to be a part of the Alfheim family!\n\n\n";

use strict;
use warnings;
use File::Slurp;
use File::Path;

my $script_root = \$ENV{PWD};

system('/usr/bin/chmod a+x scripts/alnsd/pre-config.sh');
system('/usr/bin/chmod a+x scripts/alnsd/packages');

mkpath "work/airootfs/var/lib/pacman";
mkdir "work/airootfs/etc/initcpio/hooks";
mkdir "work/airootfs/etc/initcpio/install";

system('/usr/bin/yaourt --config scripts/alnsd/pacman.conf -r work/airootfs -Sy base syslinux package-query yaourt');
system 'cp' , 'scripts/alnsd/packages' , 'work/airootfs/usr/bin/';
system 'cp' , 'scripts/alnsd/pre-config.sh' , 'work/airootfs/usr/bin/';
system 'cp' , 'scripts/alnsd/mkinitcpio.conf' , 'work/airootfs/etc/mkinitcpio-archiso.conf';
system 'cp' , 'scripts/alnsd/pacman_final.conf' , 'work/airootfs/etc/pacman.conf';
system('cp -rf scripts/alnsd/pacman.d work/airootfs/etc/');
system 'cp' , 'scripts/alnsd/customize_airootfs.sh' , 'work/airootfs/usr/bin';

system('/usr/bin/arch-chroot work/airootfs /bin/bash \'pre-config.sh\'');
system('umount -l work/airootfs');
system('cp -rf scripts/alnsd/skel/root.tar.gz work/airootfs/home/archlive/');
system('cp -rf scripts/alnsd/skel/etc.tar.gz work/airootfs/home/archlive/');
system('/usr/bin/arch-chroot work/airootfs /bin/bash \'customize_airootfs.sh\'');
system('umount -l work/airootfs');

## The following will create the iso directory
## Copy the contents of the build directory to the iso directory
## Create the necessary boot files
## Make an iso from the iso directory

## Using build.sh to build the iso
system('/usr/bin/chmod a+x scripts/alnsd/build.sh');
system('/usr/bin/bash scripts/alnsd/build.sh');
