#!/usr/bin/perl

if ( $< != 0 ) {
	print "This script must be run as root\n";
	exit (0);
}

system('clear');

print "\nWelcome to Alfheim Linux non-systemd Build Toolkit!\n";
print "Here we are going to work together to build the best system\n";
print "that we can to suit your needs.  A lot of the software that\n";
print "may use on a regular basis may not be installed right out of\n";
print "the gate but we will do our best to accomodate you.\n";

print "\nThank you for choosing to be a part of the Alfheim family!\n\n\n";

use strict;
use warnings;
use File::Slurp;
use File::Path;

my $script_root = \$ENV{PWD};

system('/usr/bin/chmod a+x scripts/alnsd/pre-config.sh');
system('/usr/bin/chmod a+x scripts/alnsd/packages');

print "Creating airootfs filesystem\n";

mkpath "work/airootfs";
mkdir "rootfs";
system('dd if=/dev/zero of=rootfs/rootfs.img bs=1M count=30000');
system('mkfs.ext4 rootfs/rootfs.img');
system('mount rootfs/rootfs.img work/airootfs');

mkpath "work/airootfs/var/lib/pacman";
mkdir "work/airootfs/etc/initcpio/hooks";
mkdir "work/airootfs/etc/initcpio/install";
mkpath "work/airootfs/home/archlive";

my $base_system = qq{bash
cryptsetup
device-mapper
gcc-libs
gzip
iproute2
linux
lvm2
nano
bzip2
coreutils
dhcpcd
diffutils
e2fsprogs
elogind-openrc
file
filesystem
findutils
gawk
gettext
glibc
grep
inetutils
iputils
jfsutils
less
licenses
logrotate
man-db
man-pages
mdadm
netifrc
pacman
pciutils
pcmciautils
perl
procps-ng
psmisc
reiserfsprogs
s-nail
sed
shadow
sysfsutils
tar
texinfo
usbutils
util-linux
vi
which
xfsprogs
syslinux
package-query
yaourt};

$base_system =~ s{\n}{ }g;

system("/usr/bin/yaourt --config scripts/alnsd/pacman.conf -r work/airootfs -Sy --needed --noconfirm $base_system");

system 'cp' , 'scripts/alnsd/packages' , 'work/airootfs/usr/bin/';
system 'cp' , 'scripts/alnsd/pre-config.sh' , 'work/airootfs/usr/bin/';
system 'cp' , 'scripts/alnsd/mkinitcpio.conf' , 'work/airootfs/etc/mkinitcpio-archiso.conf';
system 'cp' , 'scripts/alnsd/customize_airootfs.sh' , 'work/airootfs/usr/bin';
system 'cp' , 'scripts/alnsd/pacman_final.conf' , 'work/airootfs/etc/pacman.conf';
system('cp -rf scripts/alnsd/pacman.d work/airootfs/etc/');
system('cp -rf scripts/alnsd/skel/pacman-init work/airootfs/init.d/')
system('cp -rf scripts/alnsd/skel/root.tar.gz work/airootfs/root/');
system('cp -rf scripts/alnsd/skel/etc.tar.gz work/airootfs/root/');

system('/usr/bin/arch-chroot work/airootfs /bin/bash \'pre-config.sh\'');
#system('umount -l work/airootfs');
system 'cp' , 'scripts/alnsd/pacman_final.conf' , 'work/airootfs/etc/pacman.conf';
system('cp -rf scripts/alnsd/pacman.d work/airootfs/etc/');
system('/usr/bin/arch-chroot work/airootfs /bin/bash \'customize_airootfs.sh\'');
#system('umount -l work/airootfs');

## The following will create the iso directory
## Copy the contents of the build directory to the iso directory
## Create the necessary boot files
## Make an iso from the iso directory

## Using build.sh to build the iso
system('/usr/bin/chmod a+x scripts/alnsd/build.sh');
system('/usr/bin/bash scripts/alnsd/build.sh');
